//@flow

export const fieldArr = [
  { id: 1, name: 'numTroop', value: 'Номер взвода', isFiltering: true },
  { id: 2, name: 'position', value: 'Должность', isFiltering: false },
  { id: 3, name: 'instGroup', value: 'Группа в институте', isFiltering: true },
  { id: 4, name: 'mobilePhone', value: 'Мобильный телефон', isFiltering: true },
  { id: 5, name: 'homePhone', value: 'Домашний телефон', isFiltering: true },
  { id: 6, name: 'faculty', value: 'Факультет', isFiltering: true },
  { id: 7, name: 'kurs', value: 'Курс', isFiltering: true },
  { id: 8, name: 'specInst', value: 'Специальность в институте', isFiltering: true },
  { id: 9, name: 'conditionsOfEducation', value: 'Условия обучения в ВУЗе', isFiltering: false },
  { id: 10, name: 'rectal', value: 'Военкомат', isFiltering: true },
  { id: 11, name: 'specialityName', value: 'Название специальности', isFiltering: true },
  { id: 12, name: 'birthday', value: 'Дата рождения', isFiltering: true },
  { id: 13, name: 'placeBirthday', value: 'Место рождения', isFiltering: true },
  { id: 14, name: 'dateOfOrder', value: 'Дата приказа о приеме', isFiltering: true },
  { id: 15, name: 'numberOfOrder', value: 'Номер приказа о приеме', isFiltering: true },
  { id: 16, name: 'citizenship', value: 'Гражданство', isFiltering: true },
  { id: 17, name: 'nationality', value: 'Национальность', isFiltering: true },
  { id: 18, name: 'familiStatys', value: 'Семейный статус', isFiltering: false },
  { id: 19, name: 'placeOfRegestration', value: 'Адрес прописки', isFiltering: true },
  { id: 20, name: 'placeOfResidence', value: 'Адрес проживания', isFiltering: true },
  { id: 21, name: 'school', value: 'Школа', isFiltering: true },
  { id: 22, name: 'yearOfAddMAI', value: 'Год поступления в МАИ', isFiltering: true },
  { id: 23, name: 'yearOfAddVK', value: 'Год поступления на ВК', isFiltering: true },
  { id: 24, name: 'yearOfEndMAI', value: 'Год окончания МАИ', isFiltering: true },
  { id: 25, name: 'yearOfEndVK', value: 'Год окончания ВК', isFiltering: true },
  { id: 26, name: 'collness', value: 'Звание', isFiltering: true },
]