// <auto-generated />
using LKS.DAL.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LKS.DAL.Migrations
{
    [DbContext(typeof(LKSDbContext))]
    [Migration("20181005132742_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LKS.Models.Cycle", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Number");

                    b.Property<string>("SpecialityName");

                    b.Property<string>("VUS");

                    b.Property<string>("VkName");

                    b.Property<string>("VuzName");

                    b.HasKey("Id");

                    b.ToTable("Cycles");
                });

            modelBuilder.Entity("LKS.Models.Prepod", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdditionalInfo");

                    b.Property<string>("Coolness");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.Property<string>("PrepodRank");

                    b.HasKey("Id");

                    b.ToTable("Prepods");
                });

            modelBuilder.Entity("LKS.Models.Relative", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Birthday");

                    b.Property<string>("FirstName");

                    b.Property<string>("HealthStatus");

                    b.Property<string>("LastName");

                    b.Property<string>("MaidenName");

                    b.Property<string>("MiddleName");

                    b.Property<string>("MobilePhone");

                    b.Property<string>("PlaceOfRegestration");

                    b.Property<string>("PlaceOfResidence");

                    b.Property<string>("RelationDegree");

                    b.Property<string>("StudentId");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Relatives");
                });

            modelBuilder.Entity("LKS.Models.Student", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AssessmentCharacteristicFinal");

                    b.Property<int>("AssessmentCharacteristicMilitarySpeialTraining");

                    b.Property<int>("AssessmentCharacteristicMilitaryTechnicalTraining");

                    b.Property<int>("AssessmentCharacteristicTacticalSpecialTraining");

                    b.Property<int>("AssessmentProtocolOneFinal");

                    b.Property<int>("AssessmentProtocolOnePractice");

                    b.Property<int>("AssessmentProtocolOneTheory");

                    b.Property<string>("AvarageScore");

                    b.Property<string>("Birthday");

                    b.Property<string>("BloodType");

                    b.Property<string>("CapSize");

                    b.Property<string>("Citizenship");

                    b.Property<string>("ClothihgSize");

                    b.Property<string>("Collness");

                    b.Property<string>("ConditionsOfEducation");

                    b.Property<string>("DateOfOrder");

                    b.Property<bool>("Exhortation");

                    b.Property<string>("Faculty");

                    b.Property<string>("FamiliStatys");

                    b.Property<string>("Fighting");

                    b.Property<string>("FirstName");

                    b.Property<string>("ForeignLanguage");

                    b.Property<string>("Growth");

                    b.Property<string>("HomePhone");

                    b.Property<string>("ImagePath");

                    b.Property<string>("InstGroup");

                    b.Property<int>("Kurs");

                    b.Property<string>("LanguageRank");

                    b.Property<string>("LastName");

                    b.Property<string>("MaskSize");

                    b.Property<string>("MiddleName");

                    b.Property<string>("Military");

                    b.Property<string>("MobilePhonec");

                    b.Property<string>("Nationality");

                    b.Property<string>("Note");

                    b.Property<string>("NumTroop");

                    b.Property<string>("NumberOfOrder");

                    b.Property<string>("PlaceBirthday");

                    b.Property<string>("PlaceOfRegestration");

                    b.Property<string>("PlaceOfResidence");

                    b.Property<bool>("ProjectOrder");

                    b.Property<string>("Rank");

                    b.Property<string>("Rectal");

                    b.Property<string>("School");

                    b.Property<string>("ShoeSize");

                    b.Property<bool>("Skill1");

                    b.Property<bool>("Skill2");

                    b.Property<bool>("Skill3");

                    b.Property<bool>("Skill4");

                    b.Property<bool>("Skill5");

                    b.Property<bool>("Skill6");

                    b.Property<string>("SpecInst");

                    b.Property<string>("Status");

                    b.Property<string>("TroopId");

                    b.Property<string>("Two_MobilePhone");

                    b.Property<string>("VO");

                    b.Property<string>("WhoseOrder");

                    b.Property<string>("YearOfAddMAI");

                    b.Property<string>("YearOfAddVK");

                    b.Property<string>("YearOfEndMAI");

                    b.Property<string>("YearOfEndVK");

                    b.Property<bool>("Zapas");

                    b.HasKey("Id");

                    b.HasIndex("TroopId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("LKS.Models.Troop", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CycleId");

                    b.Property<string>("Day");

                    b.Property<string>("NumberTroop");

                    b.Property<string>("PlatoonCommanderId");

                    b.Property<string>("PrepodId");

                    b.Property<bool>("SboriTroop");

                    b.Property<int>("StaffCount");

                    b.Property<string>("Vus");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.HasIndex("PrepodId");

                    b.ToTable("Troops");
                });

            modelBuilder.Entity("LKS.Models.Relative", b =>
                {
                    b.HasOne("LKS.Models.Student", "Student")
                        .WithMany("Relatives")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("LKS.Models.Student", b =>
                {
                    b.HasOne("LKS.Models.Troop", "Troop")
                        .WithMany("Students")
                        .HasForeignKey("TroopId");
                });

            modelBuilder.Entity("LKS.Models.Troop", b =>
                {
                    b.HasOne("LKS.Models.Cycle")
                        .WithMany("Troops")
                        .HasForeignKey("CycleId");

                    b.HasOne("LKS.Models.Prepod", "Prepod")
                        .WithMany("Troops")
                        .HasForeignKey("PrepodId");
                });
#pragma warning restore 612, 618
        }
    }
}
